COLORS = {
    "dark blue": "#00447C",
    "blue": "#0092CE",
    "grey": "#B1B3B6",
    "dark grey": "#808285",
    "sapphire blue": "#001745",
}

JEDNOSTKI = {
    "Centrum Europejskie": "CE",
    "Centrum Kształcenia Nauczycieli Języków Obcych i Edukacji Europejskiej UW": "CKNJOEE",
    "Instytut Ameryk i Europy": "IAE",
    "Wydział Archeologii": "WARCH",
    "Wydział Artes Liberales": "WAL",
    "Wydział Biologii": "WB",
    "Wydział Chemii": "WCH",
    "Wydział Dziennikarstwa, Informacji i Bibliologii": "WDIB",
    "Wydział Filozofii": "WFZ",
    "Wydział Fizyki": "WF",
    "Wydział Geografii i Studiów Regionalnych": "WGSR",
    "Wydział Geologii": "WG",
    "Wydział Historii": "WHIST",
    "Wydział Lingwistyki Stosowanej": "WLS",
    "Wydział Matematyki, Informatyki i Mechaniki": "WMIM",
    "Wydział Nauk Ekonomicznych": "WNE",
    "Wydział Nauk o Kulturze i Sztuce": "WNKS",
    "Wydział Nauk Politycznych i Studiów Międzynarodowych": "WNPSM",
    "Wydział Neofilologii": "WNF",
    "Wydział Orientalistyczny": "WO",
    "Wydział Pedagogiczny": "WPD",
    "Wydział Polonistyki": "WPL",
    "Wydział Prawa i Administracji": "WPA",
    "Wydział Psychologii": "WPS",
    "Wydział Socjologii": "WSOC",
    "Wydział Stosowanych Nauk Społecznych i Resocjalizacji": "WSNRSR",
    "Wydział Zarządzania": "WZ",
    "Interdyscyplinarne Centrum Modelowania Matematycznego i Komputerowego": "ICM",
    "Centrum Innowacji i Badań Edukacyjnych": "CIBE*",
    "Międzynarodowe Centrum Zarządzania": "MCZ",
    "Ośrodek Badań nad Migracjami": "OBM",
    "Centrum Archeologii Śródziemnomorskiej im. K. Michałowskiego": "CAS",
    "Centrum Nauczania Języków Obcych": "CNJO",
    "Centrum Nowych Technologii UW CeNT": "CeNT",
    "Studium Wychowania Fizycznego i Sportu": "SWFS",
    "Wydział Medyczny": "WM",
    "Biblioteka Uniwersytecka w Warszawie (BUW)": "BUW",
    "Centrum Kompetencji Cyfrowych Uniwersytetu Warszawskiego": "CKCUW",
    "Centrum Nauk Biologiczno-Chemicznych UW": "CNBC",
    "Centrum Transferu Technologii i Wiedzy": "CTTW",
    "Centrum Współpracy i Dialogu Uniwersytetu Warszawskiego": "CWID",
    "Biuro Gospodarczo-Logistyczne": "BGL",
    "Biuro Spraw Socjalnych": "BSSOC",
    "inna jednostka": "Inna",
    "Pion Prorektora ds. Badań": "Rektorat",
    "Pion Prorektora ds. Rozwoju": "Rektorat",
    "Pion Prorektora ds. Studentów i Jakości Kształcenia": "Rektorat",
    "Pion Prorektora ds. Współpracy i Spraw Pracowniczych": "Rektorat",
    "Pion Rektora": "Rektorat",
    "Środowiskowe Laboratorium Ciężkich Jonów w Uniwersytecie Warszawskim": "SLCJ",
    "Uniwersytet Otwarty Uniwersytetu Warszawskiego": "UO",
    "Wydawnictwa UW": "WUW",
    "Inna": "Inna",
    "Pion Kanclerza UW": "Kanclerz",
    "Szkoła Doktorska Nauk Ścisłych i Przyrodniczych": "SDNŚ",
    "Szkoła Doktorska Nauk Humanistycznych": "SDNH",
    "Szkoła Doktorska Nauk Społecznych": "SDNS",
    "Międzydziedzinowa Szkoła Doktorska": "MSD",
}
