COLORS = {
    "dark blue": "#00447C",
    "blue": "#0092CE",
    "grey": "#B1B3B6",
    "dark grey": "#808285",
    "sapphire blue": "#001745",
}

JEDNOSTKI = {
    "Centrum Europejskie": "CE",
    "Centrum Kształcenia Nauczycieli Języków Obcych i Edukacji Europejskiej UW": "CKNJOEE",
    "Instytut Ameryk i Europy": "IAE",
    "Wydział Archeologii": "WARCH",
    "Wydział Artes Liberales": "WAL",
    "Wydział Biologii": "WB",
    "Wydział Chemii": "WCH",
    "Wydział Dziennikarstwa, Informacji i Bibliologii": "WDIB",
    "Wydział Filozofii": "WFZ",
    "Wydział Fizyki": "WF",
    "Wydział Geografii i Studiów Regionalnych": "WGSR",
    "Wydział Geologii": "WG",
    "Wydział Historii": "WHIST",
    "Wydział Lingwistyki Stosowanej": "WLS",
    "Wydział Matematyki, Informatyki i Mechaniki": "WMIM",
    "Wydział Nauk Ekonomicznych": "WNE",
    "Wydział Nauk o Kulturze i Sztuce": "WNKS",
    "Wydział Nauk Politycznych i Studiów Międzynarodowych": "WNPSM",
    "Wydział Neofilologii": "WNF",
    "Wydział Orientalistyczny": "WO",
    "Wydział Pedagogiczny": "WPD",
    "Wydział Polonistyki": "WPL",
    "Wydział Prawa i Administracji": "WPA",
    "Wydział Psychologii": "WPS",
    "Wydział Socjologii": "WSOC",
    "Wydział Stosowanych Nauk Społecznych i Resocjalizacji": "WSNRSR",
    "Wydział Zarządzania": "WZ",
    "Interdyscyplinarne Centrum Modelowania Matematycznego i Komputerowego": "ICM",
    "Centrum Innowacji i Badań Edukacyjnych": "CIBE*",
    "Międzynarodowe Centrum Zarządzania": "MCZ",
    "Ośrodek Badań nad Migracjami": "OBM",
    "Centrum Archeologii Śródziemnomorskiej im. K. Michałowskiego": "CAS",
    "Centrum Nauczania Języków Obcych": "CNJO",
    "Centrum Nowych Technologii UW CeNT": "CeNT",
    "Studium Wychowania Fizycznego i Sportu": "SWFS",
    "Wydział Medyczny": "WM",
    "Biblioteka Uniwersytecka w Warszawie (BUW)": "BUW",
    "Centrum Kompetencji Cyfrowych Uniwersytetu Warszawskiego": "CKCUW",
    "Centrum Nauk Biologiczno-Chemicznych UW": "CNBC",
    "Centrum Transferu Technologii i Wiedzy": "CTTW",
    "Centrum Współpracy i Dialogu Uniwersytetu Warszawskiego": "CWID",
    "Biuro Gospodarczo-Logistyczne": "BGL",
    "Biuro Spraw Socjalnych": "BSSOC",
    "inna jednostka": "Inna",
    "Pion Prorektora ds. Badań": "Rektorat",
    "Pion Prorektora ds. Rozwoju": "Rektorat",
    "Pion Prorektora ds. Studentów i Jakości Kształcenia": "Rektorat",
    "Pion Prorektora ds. Współpracy i Spraw Pracowniczych": "Rektorat",
    "Pion Rektora": "Rektorat",
    "Środowiskowe Laboratorium Ciężkich Jonów w Uniwersytecie Warszawskim": "SLCJ",
    "Uniwersytet Otwarty Uniwersytetu Warszawskiego": "UO",
    "Wydawnictwa UW": "WUW",
    "Inna": "Inna",
    "Pion Kanclerza UW": "Kanclerz",
    "Szkoła Doktorska Nauk Ścisłych i Przyrodniczych": "SDNŚ",
    "Szkoła Doktorska Nauk Humanistycznych": "SDNH",
    "Szkoła Doktorska Nauk Społecznych": "SDNS",
    "Międzydziedzinowa Szkoła Doktorska": "MSD",
    "W obecnym semestrze nie dojeżdzam na uczelnię": 0,
}

EMISSION = {
    "Samochód (spalinowy)": 0.17067,
    "Motocykl / skuter (spalinowy)": 0.11355,
    "Samochód elektryczny": 0.0514,
    "Autobus miejski": 0.0965,
    "Tramwaj": 0.098,
    "Metro": 0.098,
    "Pociąg": 0.098,
    "Pieszo": 0,
    "Rower tradycyjny": 0,
    "Samochód hybrydowy": 0.12004,
    "Benzyna": 0.17048,
    "Diesel": 0.1708241,
    "Samolot": 0.15102,
    "Skuter elektryczny": 0.0165,
    "Hulajnoga elektryczna": 0.0165,
    "Rower elektryczny": 0.0165,
    "Benzynowy": 0.17048,
    "Deisel": 0.1708241,
    "Hybrydowy": 0.12004,
    "Elektryczny": 0.0514,
}

N_TEACHERS = 4294
N_NON_TEACHERS = 4058
N_BACHELORS = 19754
N_MASTERS = 16303
N_PHDS = 1529
N_WEEKENDERS = 2898
N_STUDENTS = N_BACHELORS + N_MASTERS + N_PHDS + N_WEEKENDERS
N_ALL = N_TEACHERS + N_NON_TEACHERS + N_STUDENTS
