---
title: "Wstępny raport z analiz emisji na UW"
author: "Mikołaj Biesaga"
toc: true
toc-depth: 3
toc-location: left
execute:
  echo: false
format:
  html:
    grid:
      margin-width: 10px
    embed-resources: true
reference-location: margin
citation-location: margin
---

## Wstęp

Zajęło mi to moment dłużej niż planowałem, bo się zorientowałem, że był błąd w
niektórych moich obliczeniach. Niestety emisja była niedoszacowana jeśli chodzi
o wyjazdy...

### Dojazdy na uczelnie

Co do liczenia korekty to moim zdaniem ona na nic się nie zda bo tak naprawdę
korekta jest tylko dla semestru zimowego bo tylko semestr zimowy był w 2024 roku.
Poza tym, jeśli ktoś był na Erasmusie 45 dni i dojeżdżał 45 dni w semestrze 
zimowym to cała jego emisja zniknie. Mimo że tak naprawdę ma zajęcia tylko 3
razy w tygodniu, a na Erasmusie był 6 i pół tygodnia. Moim zdaniem wyniki z
korektą to jest artefakt i bym go nie uwzględniał.

Grupa | Semestr letni | Semestr letni (korekta) | Semestr zimowy | Semestr zimowy (korekta)
------|:-------------:|:-----------------------:|:--------------:|:------------:
Osoby studenckie (plus osoby doktoranckie) | 8047376.54 | | 8493050.71 | 8267621.74
Nauczyciele i nauczycielki akademickie | 184433.82 | | 183370.98 | 176581.06
Pozostałe pracownice i pracownicy | 465125.31 | | 458434.91 | 454034.01

Poprzednio mam wrażenie, że napisałem tutaj głupotę, bo tylko u osób studenckich
jest tak jak powinno być (razem z podyplomówką), czyli latem mniejsza emisja
niż zimą.

### Podróże między kampusami

Zapomniałem tylko dodać, że tutaj wymnażam wszystko razy dwa no bo są dwa 
semestry, więc zakładam, że osoby studenckie przemieszczają się między kampusami
przez 30 tygodni (nie wliczałem tutaj ludzi na podyplomówkach), osoby
nauczycielskie -- 45, a pracownice i pracownicy -- 48.

Grupa | Emisja
------|:-----:
Osoby studenckie (+doktoranckie) | 479495.56
Nauczyciele i nauczycielki akademickie | 17745.18
Pracownicy i pracownice (nie nauczyciele) | 82789.17

### Praktyki i staże

Jeśli chodzi o praktyki i staże to zdecydowana większość ludzi robiła je w
trakcie roku akademickiego poza godzinami zajęć. Emisję liczyłem tak samo jak w
poprzednich przypadkach. Nie jestem jednak w stanie policzyć emisji dla każdej z
grup. Mogę to zrobić tylko dla wszystkich razem. Wynika to z faktu, że nie wiem
jaka jest dla poszczególnej kategorii (rodzaju praktyk) liczebność na całym UW.

Grupa | Liczebność | Emisja
------|:----------:|:------:
Praktyki w lecie | 76|
Praktyki w roku akademickim | 179 |
Praktyki zamiast zajęć | 28 |
SUMA | 283 | 600266.16

### Obozy i wyjazdy na staże poza Warszawę

Tutaj był błąd dlatego mimo że teraz liczę podróż tylko w jedną stronę emisja
wzrosła a nie spadła.

Grupa | Liczebność | Emisja
------|:----------:|:------:
Obozy w lecie | 106 |
Obozy w roku akademickim | 65 |
Obozy zamiast zajęć | 141 |
SUMA | 312 | 524659.77

### Erasmus

Tutaj też był błąd dlatego wynik dla osób studenckich jest wyższy niż poprzednio
mimo że teraz liczę podróż tylko w jedną stronę.

Grupa | Osoby studenckie | Osoby nauczycielskie | Pracownice i pracownicy 
------|:----------------:|:--------------------:|:-----------------------:
Erasmus w lecie (n) | 8 | 7 | 4
Erasmus zamiast zajęć (n) | 74 | 96 | 80
Emisja | 687763.68 | 17961.82 | 29360.49

### Samochody służbowe

Użyłem tutaj tej samej metodologii co w przypadku pozostałych kategorii. W 
poniższej tabeli wyniki.

Nauczyciele i nauczycielki akademickie | Pracownice i pracownicy (nie nauczyciele)
:------------------------------------:|:----------------------------------------:
45103.16 | 27027.21

## Podsumowanie

Na razie nie zsumowałem wszystkich wyników, bo zanim to zrobię pewnie musimy
znaleźć odpowiedzi na parę pytań. Między innymi:

1. Czy jest sens liczyć skorygowane dojazdy na uczelnie? Według mnie dość
umiarkowany. Po pierwsze, dlatego, że jednak to wszystko opiera się na dość dużym
przybliżeniu. Poczynając od próby, którą mamy. W żadnym mierze nie jest ona
reprezentatywna dla tych jednostek ani też grup. Po drugie, dlatego, że nie do
końca wiem jak należałoby skorygować dojazdy na uczelnie. Pewnie można po prostu
jeden semestr ludziom, którzy byli na Erasmusie wywalić z obliczeń. Tylko który?
Poza tym, moim zdaniem pytanie o Erasmusa jest nieprecyzyjne, bo pytamy czy ktoś
był na Erasmusie w roku kalendarzowym 2024. Co trochę komplikuje sprawę, bo mógł
być w semestrze letnim 2024 roku, a my pytamy o dojazdy zima i lato tego roku
akademickiego.

2. Czy na pewno chcemy liczyć, że tygodni w semestrze jest 20?

3. Czy nie powinniśmy każdej podróży na uczelnie liczyć podwójnie? Jednak
ludzie zazwyczaj wracają z uczelni do domu.

4. Czy powinienem policzyć też Erasmusa dla pracownic i pracowników?

Ogólnie, to są jakieś wyniki, ale ciężko mi powiedzieć na ile one są dobre, a na
ile nie. Głównie dlatego, że nie wiem jaki powinien być zakres. Oczywiście ja
sobie napisałem multum jakiś testów jednostkowych, które sprawdzają czy moje
obliczenia są poprawne, ale tak czy inaczej ciężko mi powiedzieć czy te liczby
mają sens.

[Tutaj](https://github.com/MikoBie/pejk) znajdziecie repozytorium, w którym jest
cały kod do liczenia.